name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
#  schedule:
#    - cron: "0 6 * * 1" # Weekly Monday 6am UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  tests:
    needs: lint
    uses: ./.github/workflows/tests.yml
    secrets: inherit
